# Site settings
title: Edge Play
email: 534332648@qq.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: AlphaTan1994
github_username: AlphaBlackTan

# Build settings
markdown: kramdown
